### ISSUE TITLE
Some users aren't assigned roles

### ISSUE THREAD

**Issue by pkfoury** [BoilerMake/backend#99]
There are gaps in the `role_user` table even though the user exists in `users`. This prevents their application from being created and/or shown.

![screen shot 2018-09-03 at 3 20 12 pm](https://user-images.githubusercontent.com/22671016/44999737-7a2fc280-af8d-11e8-9ef6-86bb753fd2de.png)

**Comment by pkfoury** [comment]
This is related to auditing when users are added. Snippet of the stacktrace:

`[2018-08-21 16:36:15] production.ERROR: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user_agent' at row 1 (SQL: insert into audits (old_values, new_values, event, auditable_id, auditable_type, user_id, url, ip_address, user_agent, updated_at, created_at) values ([], `...

**Comment by nickysemenza** [comment]
oh hm this is my fault, i think i did a hotfix last year and didn't write a migration :) (bad!) 
the issue is the column is a varchar right now: https://github.com/boilermake/backend/blob/master/database/migrations/2017_08_02_060108_create_audits_table.php#L38

you'll need a migration to make it a TEXT, something like `$table->text('user_agent)->change();`

https://laravel.com/docs/5.7/migrations#modifying-columns

**Comment by nickysemenza** [comment]
also you'll need to backfill the roles following user ids when fixed: `select id from users where id not in (select user_id from role_user)`, just 
```
INSERT INTO `role_user` (`user_id`, `role_id`) VALUES ('USER_ID', '1');
``` 
for each
